# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'absensi' do
  pod 'AppCenter/Crashes', '~> 3.3.2'
  pod 'AppCenter/Analytics', '~> 3.3.2'
  pod 'AppCenterReactNativeShared', '~> 3.1.1'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for absensi

  

  platform :ios, '9.0'
  target 'absensiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'absensi-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for absensi-tvOS

  target 'absensi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
